#!/bin/bash

echo "Downloading OpenMPI Source"
wget https://www.open-mpi.org/software/ompi/v2.0/downloads/openmpi-2.0.1.tar.gz
tar zxvf openmpi-2.0.1.tar.gz
echo "Configuring and buidling OpenMPI"
cd openmpi-2.0.1
./configure --prefix=`pwd`/../openmpi
make -j4
make install
cd ..

