#!/bin/bash

if [ -d "openmpi" ]; then
    echo "Using cached OpenMPI"
else
    echo "Downloading OpenMPI Source"
    wget https://www.open-mpi.org/software/ompi/v2.0/downloads/openmpi-2.0.1.tar.gz
    tar zxf openmpi-2.0.1.tar.gz
    echo "Configuring and building OpenMPI"
    cd openmpi-2.0.1
    ./configure --prefix=`pwd`/../openmpi &> openmpi.configure
    make -j4 &> openmpi.make
    make install &> openmpi.install
    cd ..
fi
